services:
  - type: web
    name: ai-ecotrack-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:5000
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: USER_AGENT
        sync: false
    autoDeploy: true
    plan: free

  - type: web
    name: ai-ecotrack-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    rootDir: frontend
    autoDeploy: true
    plan: free
